# Problem 2: Even Fibonacci Numbers
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the
# first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed n, find the sum of the even-valued terms

def fibo_even_sum(n):
    fibo_nums = [1, 2]
    next_num = sum(fibo_nums[-2:])
    while next_num <= n:
        fibo_nums.append(next_num)
        next_num = sum(fibo_nums[-2:])
    return sum([x for x in fibo_nums if x % 2 == 0])


def main():
    n = int(input("enter an upper limit: "))
    print(f"the sum of even fibonacci up to {n} is: {fibo_even_sum(n)}")


if __name__ == "__main__":
    main()
